version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - FLASK_APP=core/server.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///core/store.sqlite3
    ports:
      - "7755:7755"
    volumes:
      - .:/app
